/*
 * This source file was generated by the Gradle 'init' task
 */
package sum.of.fibonacci.series;

import java.util.Scanner;

public class App {
    // function to calculate the factorial of a number
    public static double factorial(int num) {
        double prod = 1;
        // 3! = 1*2*3
        for (int i = 1; i <= num; i++){
            prod = prod * i;
        }
        return prod;
    }

    // Calculate sum of factorial.
    public static double sumOfFactorial(int n) {
        double sum = 0;

        for (int i = 1; i <= n; i++) {
            sum = sum + factorial(i);
        }
        return sum;
    }

    public static void main(String[] args) {
        
        Scanner ss =  new Scanner(System.in);
        int n;

        System.out.println("Please enter the nth term: ");
        n = ss.nextInt();

        System.out.println(sumOfFactorial(n));
    }
}
